import type { Metadata } from "next";
import "./globals.css";
import SessionProvider from '@/context/sessionProvider'
import { getServerSession } from "next-auth";
import LayoutSetting from "./layoutSetting";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import { authOptions } from "@/lib/auth";
import TopProgressBar from "@/components/TopProgressbar";
import { DialogProvider } from "@/context/DialogContext";

export const metadata: Metadata = {
  title: "Ecommerce-website",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions)
  return (
    <>
      <html lang="en">
        <head>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
          <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Thai:wght@100..900&display=swap" rel="stylesheet"></link>
        </head>
        <body className="bg-white text-black">
          <SessionProvider session={session}>
            <DialogProvider>
              <LayoutSetting>
                <TopProgressBar />
                {children}
              </LayoutSetting>
            </DialogProvider>
            <ToastContainer
              position="top-right"
              autoClose={1500}
              hideProgressBar
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
            />
          </SessionProvider>
        </body>
      </html>
    </>
  );
}