import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

// import components
import Navbar from "@/components/Navbar";

const inter = JetBrains_Mono({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "web portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-5xl mx-auto min-h-screen`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}